version: 2.1

parameters:
  load_test:
    type: boolean
    default: false
  version:
    type: string
    default: ""

jobs:
  load-test:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Install Apache Benchmark
          command: |
            sudo apt-get update && sudo apt-get install -y apache2-utils
      - run:
          name: Generate Load
          command: |
            version="<< pipeline.parameters.version >>"
            ab -T 'application/json' -p load-test/test-appointment.json -c 1 -n 300 http://staff.eu.bizdata-demo.vamp-dev.cloud/$version/appointments/attend

  no-op:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Nothing to do
          command: |
            echo "Nothing to do (other than keep the build green)"

workflows:
  version: 2
  
  load-test:
    when: 
      and:
        - << pipeline.parameters.load_test >>
        - << pipeline.parameters.version >>
    jobs:
      - load-test

  noop:
    when:
      and:
      - not: << pipeline.parameters.load_test >>
    jobs:
      - no-op